### ISSUE TITLE
[Back] use openApi standard to write Scratchy REST API

### ISSUE THREAD

**Issue by yannis-mlgrn** [mdl29/scratchy#96] opened 2021-04-24 17:49 UTC
https://www.openapis.org/

Publish Scratchy REST API using Open API standard.

**Comment by js-all** [comment] 2021-04-25 09:49
we said no full backend rewrite, if you want to make the current backend code follow the openAPI specifications, then go for it
but why rewrite the backend now ? the API is already pretty much done, and it shouldn't require much more work to complete it for V2.

**Comment by Draeggon** [comment] 2021-04-25 10:19
apparently it is a swagger that will be imported into insomnia

**Comment by Draeggon** [comment] 2021-04-25 10:21
isn't that issue a duplicate of #91

**Comment by Benvii** [comment] 2021-04-25 20:43
> isn't that issue a duplicate of #91

No it's not a duplicate, #91 is about creating a javascript library that will consume the API for the front.



> we said no full backend rewrite, if you want to make the current backend code follow the openAPI specifications, then go for it
> but why rewrite the backend now ? the API is already pretty much done, and it shouldn't require much more work to complete it for V2.

It shouldn't require a full rewrite as we have already respected the rest full convention.

**Comment by js-all** [comment] 2021-04-25 20:45
> > we said no full backend rewrite, if you want to make the current backend code follow the openAPI specifications, then go for it
> > but why rewrite the backend now ? the API is already pretty much done, and it shouldn't require much more work to complete it for V2.
> 
> It shouldn't require a full rewrite as we have already respected the rest full convention.

the issue isn't really explained properly, so i though he was talking about using openAPI to generate boilerplate code for the backend (because that is mentioned somewhere on the openAPI website)

**Comment by Benvii** [comment] 2021-04-25 20:49
As we use `flask_restful` someone should take a look at https://github.com/rantav/flask-restful-swagger#flask-restful-swagger

But I've a doubt, I don't think we are correctly using our model && `flask_restful`.

**Closed** 2021-05-09 06:54 UTC
Labels: enhancement, 🔧 Backend
