### ISSUE TITLE
[tools] create a shell script to add test data into the server

### ISSUE THREAD

**Issue by ritorizo** [mdl29/scratchy#194] opened 2021-05-29 15:21 UTC
Create an helper script to ~~create a venv and install dependencies~~, add testing data into the server.

**Comment by Benvii** [comment] 2021-05-30 19:33
Is it a duplicate of #190 ? i think it's somehow linked

**Comment by Draeggon** [comment] 2021-05-30 19:37
not #190 but #182 i think

**Comment by yannis-mlgrn** [comment] 2022-02-22 19:14
The script is already present :  [test.py](https://github.com/mdl29/scratchy/blob/dev/server/scratchy_server/test/test.py)
for run the test file :
 ``` bash
<scratchy/server/scratchy-server/test>$ python test.py
```

**Closed by yannis-mlgrn** 2022-02-22 19:14 UTC
Labels: enhancement, 🔧 Backend

**Comment by Draeggon** [comment] 2022-02-26 14:28
test.py test the api but it erase the database after him, so it doesn't add testing data to the server
